# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Continuous Integration

on:
  push:
    tags:
      - '*'
    branches:
      - main

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  ###################################################
  # BUILD
  ###################################################

  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Build
        shell: bash
        run: |
          dotnet tool restore
          dotnet cake

  ###################################################
  # PUBLISH
  ###################################################

  publish:
    name: Publish
    needs: [build]
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Publish
        shell: bash
        run: |
          dotnet tool restore
          dotnet cake --target="publish" \
            --nuget-key="${{secrets.NUGET_API_KEY}}"